### ISSUE TITLE
check_nrpe from WIndows NSClient to Windows NSClient SHort Read

### ISSUE THREAD

**Issue by willemdh** [mickem/nscp#266]
Hello,

I'm trying to use check_nrpe in the NSClient++ installation folder to connect to another NSClient++ on a remote WIndows. The IP is in the allowed ip list. I get:
```
PS C:\Program Files\NSClient++> ./check_nrpe -H srv2012test -c check_ms_win_updates
Error: Failed to connect to: srv2012test:5666 :short read
```
What is required to do such a thing?

On the target:

```
[/settings/NRPE/client]
channel = NRPE

[/settings/NRPE/client/targets/default]
timeout = 30
verify mode = none
payload length = 1024
use ssl = 1

[/settings/NRPE/server]
allow arguments = true
allow nasty characters = true
extended response = false
insecure = true 
port = 5666
ssl options = no-sslv2,no-sslv3
timeout = 120
verify mode = none
use ssl = 1
```

On the source:

```
[/settings/NRPE/client]
channel = NRPE

[/settings/NRPE/client/targets/default]
timeout = 60
verify mode = none
payload length = 1024
use ssl = 1

[/settings/NRPE/server]
allow arguments = true
allow nasty characters = true
extended response = false
insecure = true 
port = 5666
ssl options = no-sslv2,no-sslv3
timeout = 3600
verify mode = none
use ssl = 1
```

A telnet from source to target on port 5666 seems to work.. Connecting from Nagios also works.

**Comment by ziesemer** [comment]
I'm apparently having the exact same issue.  Was driving me a bit crazy yesterday, and I see you posted this since.

In my case - and hopefully simplifying the issue - I can't even get `check_nrpe` working locally to itself on a default installation of either `NSCP-0.4.4.19-x64.msi` or `NSCP-0.5.0.31-x64.msi`:

    C:\Program Files\NSClient++>check_nrpe.exe host=127.0.0.1
    Error: Failed to connect to: 127.0.0.1:5666 :short read

`nsclient.log` shows the following for the above attempt:

    error:c:\source\master\include\socket/connection.hpp:257: Failed to establish secure connection: no certificate returned: 178

So it appears that the client may not be passing a required client certificate - and given your above attempts, I'd hazard a guess that client certificate support on the client may be broken here?

Per http://forums.nsclient.org/t/check-nrpe-and-security-thoughts/3936/4 , I've even tried calling this as:

    C:\Program Files\NSClient++>check_nrpe.exe host=127.0.0.1 certificate=security\certificate.pem dh=security\nrpe_dh_512.pem
    Error: Failed to connect to: 127.0.0.1:5666 :short read

... but with no improvement.

Note that I am not looking to undo any available security options here, so I am *not* attempting to set `insecure = true` and/or `verify mode = none` - but yet we're seeing an identical error...

I've also been referencing https://www.medin.name/blog/2012/12/02/securing-nrpe-with-certificate-based-authentication/ - but would hope for an updated article that reflects the current command-line argument standards being used by the current NSClient++ versions (`key=value`, vs. `--key value`, etc.).

FYI, the argument help to `check_nrpe` is also a bit suspect:

    C:\Program Files\NSClient++>check_nrpe.exe --help
      ...
      certificate=ARG      Length of payload (has to be same as on the server)
      dh=ARG               Length of payload (has to be same as on the server)
      ...

**Comment by mickem** [comment]
My guess would be insecure missmatch...

Server has:

insecure=true

so client needs the same...

```
./check_nrpe -H srv2012test --insecure -c check_ms_win_updates
```

**Comment by willemdh** [comment]
Nice!! That works indeed. :)
