### ISSUE TITLE
NSClient Setup Wizard ended prematurely

### ISSUE THREAD

**Issue by Elvisms** [mickem/nscp#317]
Good afternoon.

I'm trying to install NSClient++ (x64) version 4.4.19 on Windows Server 2008 R2 Enterprise and, when i finish the wizard, an error message pops up:

NSClient++ (x64) Setup Wizard ended prematurely because of an error. Your system has not been modified. To install this program at latter time, run Setup Wizard again. Click the Finish button to exit the Setup Wizard

Why this error occurs? How can i fix this?
I appreciate any help :)

Regards

**Comment by mickem** [comment]
Can you do a logged install and post the logs (or relevant bits)?

msiexec /l* log.txt /i <MSI FILE>

**Comment by mickem** [comment]
Please reopen this if you can resproduce it on 0.5.1

**Comment by bdpavers** [comment]
Got the same error installing it on some of my Windows Server 2016 Standard with the latest version of NSClient 0.5.1.44 x64 particularly the server running with DFS service. I need to stop the service to successfully install them. Hope this helps.

**Comment by mickem** [comment]
Could you provide the logs I asked for above i.e. run:

```
msiexec /l* log.txt /i <MSI FILE>
```

**Comment by mickem** [comment]
Please reopen this with log fro mthe installer

**Comment by ccampositpro** [comment]
Hi, @mickem good afternoon!

My name is Carlos Campos and I´m trying ncpa 0.5.2.35 on Windows Server 2016 and I am receiving the same error of another colleague. NSclient ++ (x64) Setup Wizard ended prematurely. I configured registry key for verbose log of windows installer using microsoft official document (https://support.microsoft.com/en-us/help/223300/how-to-enable-windows-installer-logging) and when I am trying install ncpa agent,the attached file is generated on %temp% folder on this server
[MSI16608.LOG](https://github.com/mickem/nscp/files/4554215/MSI16608.LOG). In paralell, I am searching another colleague that can have the same situation that me. While, I was talking this text, came my mind the possibility using some advanced trobleshooting tools as regmon or procmon from sysinternals suite. For while, only this. I´m sorry for bad english, because I´m studying and thank you his attention. 
[MSI16608.LOG](https://github.com/mickem/nscp/files/4554295/MSI16608.LOG)
