### ISSUE TITLE
I have a question about the check_nt

### ISSUE THREAD

**Issue by wangxd0206** [mickem/nscp#394]
host  only have 64G momery ,  but  I used  check_nt MENUSE command      the result display    
 	Memory usage: total:130300.40 MB - used: 9940.07 MB (8%) - free: 120360.33 MB (92%) 
who can tall me  why？ 

nsclient version is  NSClient++ 0,4,1,73 or NSClient++ 0.5.0.62

**Comment by box293** [comment]
This is because the pagefile is being taken into account.

The following KB article provides a solution:

https://support.nagios.com/kb/article.php?id=169

Even if you don't have Nagios XI, the nrpe example should help.

More detailed examples here:

http://sites.box293.com/nagios/guides/common-checks/memory-usage

**Comment by mickem** [comment]
Closing this as the question was answered excellently by @box293
