### ISSUE TITLE
Install multiple NSClient++ via .msi/.mst

### ISSUE THREAD

**Issue by uclara** [mickem/nscp#429]
Hi,

I'm trying to create transforms (.mst) to install the NSClient++ agent multiple times, in different Program-Paths and different Service-Names. Using the Orca-Tool from MS this works fine for a single installation. As soon I try to install the second instance I get a "Windows Installer reconfigured the product.".

Which GUIDs should I change in the original .msi files (or better with the transform file) to get coexisting these two instances on the same server?

Background: we differentiate system and application monitoring, which are operated by different teams. For this reason, we would like to have the option to install NSClient ++ twice.
We also want to customize both instances (different Program-Path, different Service-Name, ecc.) so that an unwanted installation of the standard NSClient ++ .msi package does not alter or damage either.

Ulli

**Comment by mickem** [comment]
Not really sure why you would need to install multiple instances.
I think it is simpler to have multiple services using the same binary so that is what I would do.

Using the --settings option on the service command line will allow you to have separate configs, further customizing the paths will allow you to have separate scripts folder if required.

You can also you "include" in the config to allow multiple layers of config over the same service which is another way to achive similar results.

The only reason I see for having multiple installations is to have multiple versions which is not really supported by the installer, then the ZIP files would be the way to go"out of the box".

**Comment by solvingJ** [comment]
FYI, In large enterprise space, it's not uncommon for multiple service providers to manage different apps and services in an environment, in addition to the enterprise managing the infrastructure. It does happen where these different teams want/need to have their own independent monitoring solutions side by side. If two happen to use NSClient-based solutions, it comes up.  I haven't seen anyone try to do two installs on the same machines before (other workarounds were used) but it would be a useful capability if it worked without significant issues.

**Comment by mickem** [comment]
I understand the problem but with two service with individual config you can achive that...

However with latest version of 0.5.1 there is a "seconday msi" when can be used to install it side by side.

The problem is that MSI is not designed for installing the same tool twice as a bundle only has one "upgrade code" to manage updates...

// Michael Medin

**Comment by mickem** [comment]
Last few builds o 0.5.1 contains two installers one (the old one) NSCP as well as a seconday_NSC which will allow you to install two separate version side by side...
